# Generated by Django 3.2.23 on 2024-02-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disabled', 'disabled'), ('link', 'link'), ('public', 'public')], default='disabled', max_length=50)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.virtualhost')),
            ],
        ),
    ]
