# Generated by Django 3.2.23 on 2024-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualhost',
            name='check_dns',
            field=models.BooleanField(default=False),
        ),
    ]
