# Generated by Django 3.2.23 on 2024-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_virtualhost_check_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=20)),
                ('files', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
