# Generated by Django 3.2.25 on 2024-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualhost',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
