# Generated by Django 3.2.25 on 2024-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_virtualhost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='root_page',
            field=models.BooleanField(default=False),
        ),
    ]
