# Generated by Django 3.2.23 on 2024-02-13 10:45

from django.db import migrations, models
import django.utils.timezone
import xabber_server_panel.base_modules.circles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=256, validators=[xabber_server_panel.base_modules.circles.models.validate_circle])),
                ('host', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('subscribes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('all_users', models.BooleanField(default=False)),
            ],
        ),
    ]
