# Generated by Django 3.2.23 on 2023-11-27 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('subscribes', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('prefix', models.CharField(max_length=10, null=True)),
            ],
            options={
                'unique_together': {('circle', 'host')},
            },
        ),
    ]
