# Generated by Django 3.2.23 on 2024-02-13 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='circle',
            unique_together={('circle', 'host')},
        ),
    ]
