# Generated by Django 3.2.23 on 2024-02-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20240130_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='all_users',
            field=models.BooleanField(default=False),
        ),
    ]
