# Generated by Django 3.2.23 on 2023-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('sql', 'internal'), ('ldap', 'LDAP')], default='sql', max_length=128),
        ),
    ]
