# Generated by Django 3.2.23 on 2024-01-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231212_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(blank=True, choices=[(0, 'read'), (1, 'write')], null=True)),
                ('app', models.CharField(choices=[('xabber_server_panel', 'xabber_server_panel'), ('xabber_server_panel.custom_auth', 'xabber_server_panel.custom_auth'), ('xabber_server_panel.users', 'xabber_server_panel.users'), ('xabber_server_panel.api', 'xabber_server_panel.api'), ('xabber_server_panel.dashboard', 'xabber_server_panel.dashboard'), ('xabber_server_panel.circles', 'xabber_server_panel.circles'), ('xabber_server_panel.groups', 'xabber_server_panel.groups'), ('xabber_server_panel.registration', 'xabber_server_panel.registration'), ('xabber_server_panel.config', 'xabber_server_panel.config'), ('modules.xabber_web', 'modules.xabber_web')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('sql', 'sql'), ('ldap', 'LDAP')], default='sql', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(null=True, to='users.CustomPermission'),
        ),
    ]
