# Generated by Django 3.2.23 on 2024-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rootpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseXmppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseXmppOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='module',
            field=models.CharField(default='home', max_length=100),
        ),
    ]
