# Generated by Django 3.2.23 on 2024-02-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240119_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='reason for blocking'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='app',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Users'), ('circles', 'Circles'), ('groups', 'Groups'), ('registration', 'Registration'), ('settings', 'Settings'), ('xabber_web', 'xabber_web')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('BANNED', 'BANNED'), ('EXPIRED', 'EXPIRED'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=255),
        ),
    ]
