# Generated by Django 3.2.25 on 2024-04-22 07:51

from django.db import migrations, models
import xabber_server_panel.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('django_command', 'Django command'), ('function', 'Function'), ('console_command', 'Console command')], default='django_command', max_length=20)),
                ('schedule', models.CharField(max_length=100, validators=[xabber_server_panel.utils.validate_cron_schedule])),
                ('args', models.TextField(blank=True, help_text='Arguments should be represented as a list of values.', null=True)),
                ('kwargs', models.TextField(blank=True, help_text='Key-value arguments should be a valid JSON.', null=True)),
                ('command', models.CharField(max_length=255)),
            ],
        ),
    ]
