# Generated by Django 3.2.23 on 2023-11-28 11:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='circle',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
