# Generated by Django 3.2.23 on 2023-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20231128_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='subscribes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
